# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test220526' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'FirebaseAuth'
pod 'GoogleSignIn'

  # Pods for test220526

end
